# Params default config with custom Theme-related and CMS specifics.

default_chroma: auto # dark or light

show_categories: true
show_tags: true
show_versions: true
show_authors: true
show_word_count: true
show_reading_time: true
show_translations: false
show_pagination: true
show_copy: true
show_popover: true

# Image processing
resize_format: webp
resize_dimensions:
  cover: [500x250, 1000x500]
  card: [500x250]

# Remote resources fetching
timeout: 5s

# JS scripts
enable_js_details: true

enable_fediverse: true